base_url = "https://blog.g3un.com/"

compile_sass = true
build_search_index = true

theme = "no-style-please"

taxonomies = [
    { name = "tag" }
]

author = "g3un"

[markdown]
permalinks_without_slash = true
highlight_code = true

[extra]
list_pages = true

add_toc = true

header_nav = [
    { name = "~home", url = "/" },
    { name = "@about", url = "/about/" },
    { name = ">post", url = "/post/" },
    { name = "*project", url = "/project/" },
    { name = "#tag", url = "/tag/" },
]

footer_nav = [
    { name = "GITHUB", url = "https://github.com/g3un/" },
    { name = "X", url = "https://x.com/g3un98/" }
]