# The URL the site will be built for
base_url = "https://blog.g3un.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "no-style-please"

[markdown]

highlight_code = true

[extra]
list_pages = true

add_toc = true

header_nav = [
    { name = "home", url = "/" },
    { name = "about", url = "/about" },
    { name = "post", url = "/post" },
    { name = "project", url = "/project" },
]

footer_nav = [
    { name = "github", url = "https://github.com/g3un", new_tab = true },
]
